import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Clock3, Instagram, MapPin, Menu, Phone, Users, X } from "lucide-react";

const facadePhoto = "/manus-storage/la-bascule-public_3b560c54.jpg";
const phone = "05 61 69 73 34";
const tel = `tel:${phone.replaceAll(" ", "")}`;

export default function LaBascule() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  useEffect(() => { document.title = "Bistrot La Bascule — Pamiers"; }, []);

  return (
    <div className="min-h-screen bg-[#f3f0e9] text-[#242b2b]">
      <header className="sticky top-0 z-50 border-b border-[#242b2b]/10 bg-[#f3f0e9]/95 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8">
          <a href="#accueil" onClick={closeMenu} className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#1f7474] text-sm font-black text-white">LB</span><span><span className="block font-serif text-lg leading-none text-[#1f7474]">La Bascule</span><span className="mt-1 block text-[9px] font-bold uppercase tracking-[0.2em] text-[#687271]">Bistrot · Pamiers</span></span></a>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-[#596463] md:flex"><a href="#restaurant" className="hover:text-[#1f7474]">Le bistrot</a><a href="#groupes" className="hover:text-[#1f7474]">Groupes & événements</a><a href="#contact" className="hover:text-[#1f7474]">Contact</a><a href={tel} className="inline-flex items-center gap-2 rounded-full bg-[#1f7474] px-4 py-2.5 text-white transition-colors hover:bg-[#185b5b]"><Phone size={14} /> Réserver</a></nav>
          <button type="button" onClick={() => setMenuOpen((open) => !open)} className="rounded-full border border-[#242b2b]/15 p-2 text-[#1f7474] md:hidden" aria-label="Ouvrir le menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        </div>
        {menuOpen && <nav className="border-t border-[#242b2b]/10 bg-[#f3f0e9] px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm font-semibold text-[#596463]"><a href="#restaurant" onClick={closeMenu}>Le bistrot</a><a href="#groupes" onClick={closeMenu}>Groupes & événements</a><a href="#contact" onClick={closeMenu}>Contact</a><a href={tel} onClick={closeMenu}>Réserver par téléphone</a></div></nav>}
      </header>

      <main id="accueil">
        <section className="border-b border-[#242b2b]/10 bg-[#e5ece8]"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#b16c3b]">Cuisine du terroir · Pamiers</p><h1 className="mt-5 max-w-xl font-serif text-6xl leading-[.95] tracking-[-0.04em] text-[#1f7474] sm:text-8xl">Le goût du <em className="text-[#b16c3b]">vrai</em> moment.</h1><p className="mt-7 max-w-lg text-base leading-7 text-[#53615e]">Un bistrot convivial au cœur de Pamiers, pour déjeuner, dîner, partager un repas de groupe ou organiser un événement.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={tel} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#1f7474] px-6 py-3.5 text-sm font-bold text-white transition-colors hover:bg-[#185b5b]"><Phone size={16} /> Réserver au {phone}</a><a href="#groupes" className="inline-flex items-center justify-center gap-2 rounded-full border border-[#242b2b]/20 px-6 py-3.5 text-sm font-bold text-[#242b2b] hover:border-[#1f7474] hover:text-[#1f7474]">Organiser un repas <ArrowRight size={16} /></a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-[#71807b]"><span className="inline-flex items-center gap-2"><MapPin size={14} className="text-[#b16c3b]" /> Place Milliane, Pamiers</span><span className="inline-flex items-center gap-2"><Users size={14} className="text-[#b16c3b]" /> Jusqu’à 70 couverts</span></div></div><div className="relative overflow-hidden rounded-[1.75rem] bg-[#1f7474] p-3 shadow-[0_18px_50px_rgba(31,116,116,.14)]"><img src={facadePhoto} alt="Façade publique du Bistrot La Bascule à Pamiers" className="aspect-[4/3] w-full rounded-[1.25rem] object-cover" /><p className="px-3 py-3 text-[10px] leading-4 text-[#e5ece8]/75">Photo publique — <a href="https://www.tripadvisor.fr/Restaurant_Review-g644113-d1593029-Reviews-Bistrot_La_Bascule-Pamiers_Ariege_Occitanie.html" target="_blank" rel="noreferrer" className="underline">Tripadvisor</a>.</p></div></div></section>

        <section id="restaurant" className="mx-auto max-w-6xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#b16c3b]">L’esprit du bistrot</p><h2 className="mt-4 font-serif text-5xl leading-[.98] tracking-[-0.035em] text-[#1f7474]">Une cuisine simple, raffinée et de saison.</h2></div><div className="grid gap-8 text-[#53615e] sm:grid-cols-2"><p className="text-base leading-7">La Bascule propose une cuisine traditionnelle et régionale, avec des produits frais, des plats du marché, de la viande grillée et du poisson à la plancha.</p><p className="text-base leading-7">Déjeuner entre collègues, dîner entre amis ou repas en famille : le bistrot accueille chaque moment avec la même attention.</p></div></div><div className="mt-16 grid gap-4 border-y border-[#242b2b]/15 py-7 sm:grid-cols-3"><div className="flex items-center gap-4"><CalendarDays className="text-[#b16c3b]" size={24} strokeWidth={1.5} /><div><p className="text-sm font-bold">Du mardi au samedi</p><p className="mt-1 text-xs text-[#71807b]">Horaires à confirmer</p></div></div><div className="flex items-center gap-4"><Clock3 className="text-[#b16c3b]" size={24} strokeWidth={1.5} /><div><p className="text-sm font-bold">Réservation conseillée</p><p className="mt-1 text-xs text-[#71807b]">Par téléphone</p></div></div><div className="flex items-center gap-4"><Users className="text-[#b16c3b]" size={24} strokeWidth={1.5} /><div><p className="text-sm font-bold">Terrasse & salle</p><p className="mt-1 text-xs text-[#71807b]">Groupes et réceptions</p></div></div></div></section>

        <section id="groupes" className="bg-[#dce9e3]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#b16c3b]">Groupes & événements</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-[.98] tracking-[-0.035em] text-[#1f7474]">Un repas à organiser ? Parlons-en.</h2><p className="mt-6 max-w-xl text-base leading-7 text-[#53615e]">La Bascule accueille les repas de fêtes, séminaires, baptêmes, mariages, départs à la retraite et autres grandes occasions. Une salle et une terrasse sont disponibles selon votre événement.</p><a href={tel} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#b16c3b] px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-[#94572f]"><Phone size={16} /> Demander un devis</a></div><div className="border-l-2 border-[#b16c3b] pl-6"><p className="font-serif text-3xl italic leading-tight text-[#1f7474]">“Un cadre convivial pour les repas qui comptent.”</p><p className="mt-5 text-sm text-[#71807b]">Menus de groupe et prestations traiteur à préciser directement avec l’équipe.</p></div></div></section>

        <section id="contact" className="bg-[#1f7474] text-[#f2f7f2]"><div className="mx-auto flex max-w-6xl flex-col gap-10 px-5 py-20 lg:flex-row lg:items-end lg:justify-between lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#e3ad78]">Nous trouver</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-[.98] tracking-[-0.035em]">À bientôt à La Bascule.</h2><div className="mt-8 space-y-3 text-sm text-[#f2f7f2]/80"><p className="flex items-center gap-3"><MapPin size={16} className="text-[#e3ad78]" /> 1 Esplanade de Milliane, 09100 Pamiers</p><p className="flex items-center gap-3"><Phone size={16} className="text-[#e3ad78]" /> {phone}</p></div></div><div className="flex flex-col items-start gap-4 lg:items-end"><a href={tel} className="inline-flex items-center gap-3 rounded-full bg-[#e3ad78] px-6 py-3.5 text-sm font-bold text-[#1f7474] hover:bg-[#f1c38f]"><Phone size={16} /> Réserver une table</a><a href="https://www.facebook.com/labascule09/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-semibold underline decoration-[#e3ad78] underline-offset-4"><Instagram size={16} /> Voir la page Facebook</a></div></div></section>
      </main>
      <footer className="bg-[#185b5b] px-5 py-6 text-center text-[11px] text-[#f2f7f2]/60">© Bistrot La Bascule · Concept de démonstration — informations et visuels à valider par le restaurant.</footer>
    </div>
  );
}
